# Linear Algebra

Practicing core Linear Algebra concepts using NumPy —
matrix operations, transpose, determinant, inverse,
rank, eigenvalues, solving linear equations, norm and trace.

In [1]:
import numpy as np

## Create a matrix(3,3) and perform single number arithmatic operations

In [2]:
m1 = np.random.randint(10, 50, (3,3))

In [3]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [4]:
m1 + 50

array([[62, 68, 64],
       [85, 75, 77],
       [73, 99, 99]])

In [5]:
m1 - 20

array([[-8, -2, -6],
       [15,  5,  7],
       [ 3, 29, 29]])

In [6]:
m1 * 3

array([[ 36,  54,  42],
       [105,  75,  81],
       [ 69, 147, 147]])

In [7]:
m1 / 4

array([[ 3.  ,  4.5 ,  3.5 ],
       [ 8.75,  6.25,  6.75],
       [ 5.75, 12.25, 12.25]])

## Create 2 matrices of 3x3 and perform arithmatic operations between them

In [8]:
m = np.random.randint(10,50, (3,3))
n = np.random.randint(10,50, (3,3))

In [9]:
print(m)
print(n)

[[47 12 12]
 [27 21 27]
 [33 47 21]]
[[23 48 24]
 [19 48 34]
 [42 19 20]]


In [10]:
m + n

array([[70, 60, 36],
       [46, 69, 61],
       [75, 66, 41]])

In [11]:
m - n

array([[ 24, -36, -12],
       [  8, -27,  -7],
       [ -9,  28,   1]])

In [12]:
m * n

array([[1081,  576,  288],
       [ 513, 1008,  918],
       [1386,  893,  420]])

In [13]:
m / n

array([[2.04347826, 0.25      , 0.5       ],
       [1.42105263, 0.4375    , 0.79411765],
       [0.78571429, 2.47368421, 1.05      ]])

all the arithmatic operations we just performed above are element wise like in m*n we will get the multiplication of the elements of m and n NOT THE DOT OR VECTOR PRODUCT

## Perfom the Dot Product on any matrices of 2x2

In [14]:
a = np.random.randint(5, 20, (2,2))
b = np.random.randint(5, 20, (2,2))

In [15]:
print(a)
print(b)

[[18  8]
 [ 9  7]]
[[ 5  8]
 [11  6]]


In [16]:
# 2 methods to do it - @ , np.dot()

print(a@b)


print(np.dot(a,b))

[[178 192]
 [122 114]]
[[178 192]
 [122 114]]


## Create a Matrix and find its transpose

In [17]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [18]:
## Again 2 methods to do it - .T , np.Transpose()

print(m1.T)

print(np.transpose(m1))

[[12 35 23]
 [18 25 49]
 [14 27 49]]
[[12 35 23]
 [18 25 49]
 [14 27 49]]


## Property 1 : Transpose of a Transposed Matrix is the Original Matrix

In [19]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [20]:
transpose = m1.T
transpose

array([[12, 35, 23],
       [18, 25, 49],
       [14, 27, 49]])

In [21]:
transpose.T

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [22]:
if np.array_equal(m1, transpose.T):
  print("Property 1 is satisfied")
else:
  print("Property 1 is not satisfied")

Property 1 is satisfied


## Property 2: (Additive property) : (A+B).T = A.T + B.T

In [23]:
print(a)
print(b)

[[18  8]
 [ 9  7]]
[[ 5  8]
 [11  6]]


In [24]:
c = a + b
lhs = c.T
lhs

array([[23, 20],
       [16, 13]])

In [25]:
d = a.T + b.T
rhs = d
rhs

array([[23, 20],
       [16, 13]])

In [26]:
if np.array_equal(lhs, rhs):
  print("Property 2 is satisfied")
else:
  print("Property 2 is not satisfied")

Property 2 is satisfied


## Property 3: (Multiplicative Property): (A * B).T = B.T * A.T

In [27]:
print(a)
print(b)

[[18  8]
 [ 9  7]]
[[ 5  8]
 [11  6]]


In [28]:
c = a * b
lhs = c.T
lhs

array([[90, 99],
       [64, 42]])

In [29]:
d = b.T * a.T
a

array([[18,  8],
       [ 9,  7]])

In [30]:
if (lhs == d).all:
  print("Property 3 is satisfied")
else:
  print("Property 3 is not satisfied")


# .all means - all the elements of both matrices would be compared
# .any means - if any one of the element of bith matrices is same or not

Property 3 is satisfied


another method of property 3

In [31]:
p = np.random.randint(10, size = (2,2))
q = np.random.randint(10, size = (2,2))
if np.array_equal((p@q).T , (q.T)@(p.T)):
  print("hence proved")
else:
  print("not proved")

hence proved


## Create a 3x3 matrix and find its determinant

In [32]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [33]:
np.linalg.det(m1)


## .linalge --> means a linear algebra (IT IS A SUBMODULE FOR NUMPY)

np.float64(-4908.000000000005)

* If the determinant of matrix is 0 then ITS SINGULAR
* If the determinant of matrix is NOT EQUAL TO 0 then it is Invertible




## The Dot Product of the Original Matriz and its Inverse Matrix is equal to the IDENTITY MATRIX

In [34]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [35]:
m1_inverse = np.linalg.inv(m1)
m1_inverse

array([[ 0.0199674 ,  0.0399348 , -0.02770986],
       [ 0.22290139, -0.05419723, -0.03382233],
       [-0.23227384,  0.03545232,  0.06723716]])

In [36]:
res = m1 @ m1_inverse
res

array([[ 1.00000000e+00, -8.32667268e-17, -2.77555756e-17],
       [-5.55111512e-17,  1.00000000e+00,  3.19189120e-16],
       [-1.05471187e-15, -1.80411242e-16,  1.00000000e+00]])

In [37]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
if np.allclose(res, np.eye(3)):
  print("our dot product assumption is True")
else:
  print("our dot product assumption is False")


  # .allclose --> check the two arrays/Matrices are element wise equal or not
  # (np.allclose is used instead of == np.array_equal when comapring floating point number)

our dot product assumption is True


## Rank of a Matrix

In [39]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [40]:
np.linalg.matrix_rank(m1)

np.int64(3)

## Eigenvalues and Eigenvectors

In [41]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [42]:
eigenvalues, eigenvectors = np.linalg.eig(m1)
print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Eigenvalues:
 [87.21225515  6.92008563 -8.13234078]

Eigenvectors:
 [[-0.27364271 -0.34029261  0.32195892]
 [-0.50832283 -0.51558318 -0.77880487]
 [-0.81653388  0.78636819  0.53833579]]


## Solving System of Linear Equations (Ax = b)

In [43]:
A = np.array([[2, 1, 1],
              [1, 3, 2],
              [1, 0, 0]])

b = np.array([4, 5, 6])

x = np.linalg.solve(A, b)
x

array([  6.,  15., -23.])

In [44]:
# Verify
np.allclose(A @ x, b)

True

## Norm of a Vector / Matrix

In [45]:
v = np.array([3, 4])
np.linalg.norm(v)

np.float64(5.0)

In [46]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [47]:
np.linalg.norm(m1)

np.float64(92.59589623736032)

## Trace of a Matrix

In [48]:
m1

array([[12, 18, 14],
       [35, 25, 27],
       [23, 49, 49]])

In [49]:
np.trace(m1)

np.int64(86)

## Conclusion

In this notebook I covered:

- Matrix Arithmetic Operations
- Matrix Multiplication vs Dot Product
- Transpose & its Properties
- Determinant of a Matrix
- Inverse of a Matrix
- Rank of a Matrix
- Eigenvalues and Eigenvectors
- Solving Linear Equations (Ax = b)
- Norm of a Vector/Matrix
- Trace of a Matrix