# NumPy

**What is NumPy?**

NumPy (Numerical Python) is a library used for numerical computations.
It provides support for arrays, matrices, and many mathematical functions.

**Why NumPy?**
- Faster than Python lists
- Less memory usage
- Built-in mathematical operations
- Foundation for Pandas, Scikit-learn, etc.

In [1]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.0.2


## Dataset
We will create and use this small student dataset which contain **ages** , **marks (out of 100)** , **attendance (in percentage)** throughout this notebook for the numpy operations.


In [2]:
ages = np.array([18, 19, 20, 17, 21, 19, 18])
marks = np.array([72, 85, 60, 90, 55, 78, 88])
attendance = np.array([85.0, 92.5, 70.0, 98.0, 60.5, 88.0, 95.0])

names = np.array(["Piyush", "Vai", "Arpit", "Om", "Kabir", "Naina", "Parth"])

print("Names     :", names)
print("Ages      :", ages)
print("Marks     :", marks)
print("Attendance:", attendance)

Names     : ['Piyush' 'Vai' 'Arpit' 'Om' 'Kabir' 'Naina' 'Parth']
Ages      : [18 19 20 17 21 19 18]
Marks     : [72 85 60 90 55 78 88]
Attendance: [85.  92.5 70.  98.  60.5 88.  95. ]


## 1. Array Properties
Understanding shape, size, dimensions and datatype of an array.

In [4]:
print("Array Properties")

print("\nMarks array:", marks)
print("Shape      :", marks.shape)       # (7,) → 7 elements, 1D
print("Size       :", marks.size)        # total elements = 7
print("Dimensions :", marks.ndim)        # 1D array
print("Data Type  :", marks.dtype)       # int64
print("Item Size  :", marks.itemsize, "bytes")  # bytes per element

Array Properties

Marks array: [72 85 60 90 55 78 88]
Shape      : (7,)
Size       : 7
Dimensions : 1
Data Type  : int64
Item Size  : 8 bytes


## 2. Creating Arrays — Different Methods

In [5]:
# Zeros
empty_scores = np.zeros(7)
print("Zero scores:", empty_scores)

# Ones
passed = np.ones(7, dtype=int)
print("Passed     :", passed)

# Full
default_marks = np.full(7, 50)
print("Default    :", default_marks)

# arange
roll_numbers = np.arange(1, 8)
print("Roll Nos   :", roll_numbers)

# linspace
grade_scale = np.linspace(0, 100, 5)
print("Grade Scale:", grade_scale)

# Random integers
np.random.seed(42)
quiz_marks = np.random.randint(1, 11, size=7)
print("Quiz Marks :", quiz_marks)

Zero scores: [0. 0. 0. 0. 0. 0. 0.]
Passed     : [1 1 1 1 1 1 1]
Default    : [50 50 50 50 50 50 50]
Roll Nos   : [1 2 3 4 5 6 7]
Grade Scale: [  0.  25.  50.  75. 100.]
Quiz Marks : [ 7  4  8  5  7 10  3]


## 3. Indexing & Slicing
Accessing specific elements from the array.

In [7]:
print("All marks     :", marks)
print("First student :", marks[0])
print("Last student  :", marks[-1])      # Karan
print("First 3 marks :", marks[:3])      # Aarav, Sneha, Ravi
print("Last 3 marks  :", marks[-3:])     # Arjun, Meera, Karan
print("Alternate     :", marks[::2])

# Fancy Indexing → pick specific students
selected = marks[[0, 2, 5]]
print("Piyush, Arpit, Naina marks:", selected)

All marks     : [72 85 60 90 55 78 88]
First student : 72
Last student  : 88
First 3 marks : [72 85 60]
Last 3 marks  : [55 78 88]
Alternate     : [72 60 55 88]
Piyush, Arpit, Naina marks: [72 60 78]


## 4. Basic Math Operations
Arithmetic operations applied on arrays element-wise.

In [8]:
print("Original Marks:", marks)

# Add 5 bonus marks to everyone
bonus = marks + 5
print("After Bonus (+5) :", bonus)

# Deduct 2 for late submission
penalty = marks - 2
print("After Penalty (-2):", penalty)

# Double the marks (for weightage)
doubled = marks * 2
print("Doubled marks    :", doubled)

# Percentage out of 200 total
percentage = marks / 200 * 100
print("Percentage       :", percentage)

# Marks squared
squared = marks ** 2
print("Squared          :", squared)

Original Marks: [72 85 60 90 55 78 88]
After Bonus (+5) : [77 90 65 95 60 83 93]
After Penalty (-2): [70 83 58 88 53 76 86]
Doubled marks    : [144 170 120 180 110 156 176]
Percentage       : [36.  42.5 30.  45.  27.5 39.  44. ]
Squared          : [5184 7225 3600 8100 3025 6084 7744]


In [9]:
# Internal marks + External marks = Total
internal = np.array([20, 25, 18, 28, 15, 22, 26])
external = np.array([72, 85, 60, 90, 55, 78, 88])

total = internal + external
print("Internal:", internal)
print("External:", external)
print("Total   :", total)

difference = external - internal
print("Difference:", difference)

Internal: [20 25 18 28 15 22 26]
External: [72 85 60 90 55 78 88]
Total   : [ 92 110  78 118  70 100 114]
Difference: [52 60 42 62 40 56 62]


## 5. Statistical Operations
Descriptive statistics on marks and attendance.

In [11]:
print("Marks Statistics")
print("Marks         :", marks)
print("Mean          :", np.mean(marks))
print("Median        :", np.median(marks))
print("Mode-like Max :", np.max(marks))
print("Minimum       :", np.min(marks))
print("Maximum       :", np.max(marks))
print("Sum           :", np.sum(marks))
print("Std Deviation :", np.std(marks).round(2))
print("Variance      :", np.var(marks).round(2))
print("Range         :", np.max(marks) - np.min(marks))

print("\nAttendance Statistics")
print("Attendance    :", attendance)
print("Average Attend:", np.mean(attendance).round(2))
print("Lowest Attend :", np.min(attendance))
print("Highest Attend:", np.max(attendance))

Marks Statistics
Marks         : [72 85 60 90 55 78 88]
Mean          : 75.42857142857143
Median        : 78.0
Mode-like Max : 90
Minimum       : 55
Maximum       : 90
Sum           : 528
Std Deviation : 12.74
Variance      : 162.24
Range         : 35

Attendance Statistics
Attendance    : [85.  92.5 70.  98.  60.5 88.  95. ]
Average Attend: 84.14
Lowest Attend : 60.5
Highest Attend: 98.0


In [12]:
print("25th Percentile (Q1):", np.percentile(marks, 25))
print("50th Percentile (Q2):", np.percentile(marks, 50))
print("75th Percentile (Q3):", np.percentile(marks, 75))
print("Top 10% threshold   :", np.percentile(marks, 90))

25th Percentile (Q1): 66.0
50th Percentile (Q2): 78.0
75th Percentile (Q3): 86.5
Top 10% threshold   : 88.8


## 6. Filtering — Boolean Masking
Filter students based on conditions.

In [13]:
print("Marks:", marks)
print("Names:", names)

# Students who passed (marks >= 70)
passed_mask = marks >= 70
print("\nPassed mask   :", passed_mask)
print("Passed students:", names[passed_mask])
print("Their marks   :", marks[passed_mask])

# Students who failed
failed_mask = marks < 70
print("\nFailed students:", names[failed_mask])
print("Their marks    :", marks[failed_mask])

# Students with attendance below 75
low_attendance = attendance < 75
print("\nLow Attendance:", names[low_attendance])

# Multiple conditions → failed AND low attendance
at_risk = (marks < 70) & (attendance < 75)
print("\nAt Risk Students:", names[at_risk])

Marks: [72 85 60 90 55 78 88]
Names: ['Piyush' 'Vai' 'Arpit' 'Om' 'Kabir' 'Naina' 'Parth']

Passed mask   : [ True  True False  True False  True  True]
Passed students: ['Piyush' 'Vai' 'Om' 'Naina' 'Parth']
Their marks   : [72 85 90 78 88]

Failed students: ['Arpit' 'Kabir']
Their marks    : [60 55]

Low Attendance: ['Arpit' 'Kabir']

At Risk Students: ['Arpit' 'Kabir']


## 7. Sorting
Sort marks and find rank order.

In [15]:
print("Original Marks:", marks)

# Sort marks ascending
sorted_marks = np.sort(marks)
print("Sorted (Low→High):", sorted_marks)

# Sort descending
sorted_desc = np.sort(marks)[::-1]
print("Sorted (High→Low):", sorted_desc)

# argsort → returns index positions in sorted order
rank_order = np.argsort(marks)[::-1]
print("\nRank Order (indices):", rank_order)
print("Topper to Lowest:")
for rank, i in enumerate(rank_order):
    print(f"  Rank {rank+1}: {names[i]} → {marks[i]}")

Original Marks: [72 85 60 90 55 78 88]
Sorted (Low→High): [55 60 72 78 85 88 90]
Sorted (High→Low): [90 88 85 78 72 60 55]

Rank Order (indices): [3 6 1 5 0 2 4]
Topper to Lowest:
  Rank 1: Om → 90
  Rank 2: Parth → 88
  Rank 3: Vai → 85
  Rank 4: Naina → 78
  Rank 5: Piyush → 72
  Rank 6: Arpit → 60
  Rank 7: Kabir → 55


## 8. Reshaping Arrays
Converting 1D arrays into 2D matrix format.

In [16]:
# Combine marks of 3 subjects for 5 students → 15 values
all_marks = np.array([72, 85, 60, 90, 55,   # Subject 1
                      78, 88, 70, 65, 80,   # Subject 2
                      88, 76, 55, 92, 68])  # Subject 3

print("Original (1D):", all_marks)
print("Shape         :", all_marks.shape)

# Reshape to 3 subjects × 5 students
matrix = all_marks.reshape(3, 5)
print("\nReshaped (3x5):\n", matrix)
print("Shape:", matrix.shape)

# Transpose → 5 students × 3 subjects
transposed = matrix.T
print("\nTransposed (5x3):\n", transposed)

Original (1D): [72 85 60 90 55 78 88 70 65 80 88 76 55 92 68]
Shape         : (15,)

Reshaped (3x5):
 [[72 85 60 90 55]
 [78 88 70 65 80]
 [88 76 55 92 68]]
Shape: (3, 5)

Transposed (5x3):
 [[72 78 88]
 [85 88 76]
 [60 70 55]
 [90 65 92]
 [55 80 68]]


In [17]:
print("Marks Matrix (3 subjects x 5 students):\n", matrix)

# Average marks per student (column-wise)
avg_per_student = np.mean(matrix, axis=0)
print("\nAvg per student:", avg_per_student.round(2))

# Average marks per subject (row-wise)
avg_per_subject = np.mean(matrix, axis=1)
print("Avg per subject:", avg_per_subject.round(2))

# Total marks per student
total_per_student = np.sum(matrix, axis=0)
print("Total per student:", total_per_student)

Marks Matrix (3 subjects x 5 students):
 [[72 85 60 90 55]
 [78 88 70 65 80]
 [88 76 55 92 68]]

Avg per student: [79.33 83.   61.67 82.33 67.67]
Avg per subject: [72.4 76.2 75.8]
Total per student: [238 249 185 247 203]


## 9. Useful NumPy Functions

In [18]:
# where() → assign grades
grades = np.where(marks >= 75, "Distinction", "Pass")
print("Grades:", grades)

# clip() → cap marks between 60 and 90
clipped = np.clip(marks, 60, 90)
print("\nOriginal Marks :", marks)
print("Clipped (60-90):", clipped)

# unique() → unique ages
print("\nAll Ages   :", ages)
print("Unique Ages:", np.unique(ages))

# cumsum() → running total of marks
cumulative = np.cumsum(marks)
print("\nCumulative Marks:", cumulative)

# diff() → difference between consecutive marks
differences = np.diff(marks)
print("Differences     :", differences)

Grades: ['Pass' 'Distinction' 'Pass' 'Distinction' 'Pass' 'Distinction'
 'Distinction']

Original Marks : [72 85 60 90 55 78 88]
Clipped (60-90): [72 85 60 90 60 78 88]

All Ages   : [18 19 20 17 21 19 18]
Unique Ages: [17 18 19 20 21]

Cumulative Marks: [ 72 157 217 307 362 440 528]
Differences     : [ 13 -25  30 -35  23  10]


## 10. Math Functions

In [19]:
print("Marks:", marks)

# Square root of marks
print("Square Root    :", np.sqrt(marks).round(2))

# Log of marks (natural log)
print("Log (natural)  :", np.log(marks).round(2))

# Log base 10
print("Log base 10    :", np.log10(marks).round(2))

# Absolute values
changes = np.array([-5, 3, -8, 10, -2, 7, -1])
print("\nChanges        :", changes)
print("Absolute Values:", np.abs(changes))

# Rounding attendance
print("\nAttendance (raw)    :", attendance)
print("Rounded (0 decimal) :", np.round(attendance, 0))
print("Floor               :", np.floor(attendance))
print("Ceil                :", np.ceil(attendance))

Marks: [72 85 60 90 55 78 88]
Square Root    : [8.49 9.22 7.75 9.49 7.42 8.83 9.38]
Log (natural)  : [4.28 4.44 4.09 4.5  4.01 4.36 4.48]
Log base 10    : [1.86 1.93 1.78 1.95 1.74 1.89 1.94]

Changes        : [-5  3 -8 10 -2  7 -1]
Absolute Values: [ 5  3  8 10  2  7  1]

Attendance (raw)    : [85.  92.5 70.  98.  60.5 88.  95. ]
Rounded (0 decimal) : [85. 92. 70. 98. 60. 88. 95.]
Floor               : [85. 92. 70. 98. 60. 88. 95.]
Ceil                : [85. 93. 70. 98. 61. 88. 95.]


## Conclusion

In this notebook I covered:

- Array Creation & Properties
- Indexing & Slicing
- Math Operations
- Statistical Functions
- Filtering & Boolean Masking
- Sorting
- Reshaping & 2D Arrays
- Useful Functions (where, clip, unique, cumsum)
- Math Functions (sqrt, log, round, floor, ceil)